### ISSUE TITLE
Fountaincommand error upon integration startup

### ISSUE THREAD

**Issue by JrothSKV** [Jezza34000/home-assistant-petkit#6]
> 
> 
> 
> ```
> 
> Setup failed for custom integration 'petkit': Unable to import component: cannot import name 'FountainCommand' from 'petkitaio.constants' (/usr/local/lib/python3.12/site-packages/petkitaio/constants.py)
> 
> Traceback (most recent call last):
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
> 
>     comp = await self.hass.async_add_import_executor_job(
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
> 
>     result = self.fn(*self.args, **self.kwargs)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
> 
>     ComponentProtocol, importlib.import_module(self.pkg_path)
> 
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
> 
>     return func(*args, **kwargs)
> 
>            ^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
> 
>     return _bootstrap._gcd_import(name[level:], package, level)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
> 
>   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
> 
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
> 
>   File "/config/custom_components/petkit/__init__.py", line 9, in <module>
> 
>     from .const import DOMAIN, LOGGER, PETKIT_COORDINATOR, PLATFORMS, POLLING_INTERVAL, REGION, TIMEZONE, UPDATE_LISTENER
> 
>   File "/config/custom_components/petkit/const.py", line 8, in <module>
> 
>     from petkitaio.constants import FountainCommand, PurifierCommand
> 
> ImportError: cannot import name 'FountainCommand' from 'petkitaio.constants' (/usr/local/lib/python3.12/site-packages/petkitaio/constants.py)
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
> 
>     component = await integration.async_get_component()
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
> 
>     self._component_future.result()
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
> 
>     comp = self._get_component()
> 
>            ^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
> 
>     ComponentProtocol, importlib.import_module(self.pkg_path)
> 
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
> 
>     return func(*args, **kwargs)
> 
>            ^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
> 
>     return _bootstrap._gcd_import(name[level:], package, level)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
> 
>   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
> 
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
> 
>   File "/config/custom_components/petkit/__init__.py", line 9, in <module>
> 
>     from .const import DOMAIN, LOGGER, PETKIT_COORDINATOR, PLATFORMS, POLLING_INTERVAL, REGION, TIMEZONE, UPDATE_LISTENER
> 
>   File "/config/custom_components/petkit/const.py", line 8, in <module>
> 
>     from petkitaio.constants import FountainCommand, PurifierCommand
> 
> ImportError: cannot import name 'FountainCommand' from 'petkitaio.constants' (/usr/local/lib/python3.12/site-packages/petkitaio/constants.py)
>

**Comment by Jezza34000** [comment]
Hello, thank you for reopening the issue here. This message is due to the fact that the integration did not re-download the correct version of the API client.

You have several possibilities, if you know how to do it on your HomeAssitant's machine you must do a `pip uninstall petkitaio` then you restart and the correct version will be downloaded again

Otherwise you need to manually delete the old lib which is located in `/usr/local/lib/python3.xx/sites-packages/` and delete petkitaio

**Comment by Jezza34000** [comment]
I fix this in the new version
Download it again

**Comment by JrothSKV** [comment]
All good! Previous devices detected and Purobot Ultra added.  Let me know if I can help test in any way.

> I fix this in the new version Download it again

**Comment by Jezza34000** [comment]
Yes i don't own the Purobot Ultra could check if button action are all working as expected ?
Thank you

**Comment by JrothSKV** [comment]
If you need me to do any netcaps on traffic or run any debugs let me know. I'm not a dev but I do know networking/OS.

Stuff I've tested/noticed so far for the Ultra integration:

Cosmetic: 
- N50 odor eliminator should be N60 odor eliminator

Invalid sensors/functions:
- Lists maintenance mode functions but no maintenance mode on the ultra.

If you run scoop litter from PETKIT app it won't register in home assistant, but if your run clean litter from
Home assistant, PETKIT app registers and cleans, though you do get an error in home assistant (see screenshot)

Missing sensors/diags:
- assuming you've got a Max or X you'll see some standard sensors are missing like "last event", "last used by", etc

![image](https://github.com/user-attachments/assets/2b906f0b-4296-4fb4-a1a4-ea3c4fa00906)

![image](https://github.com/user-attachments/assets/2d4f27d7-edf3-4f6c-a6ee-88e674aa88eb)

![image](https://github.com/user-attachments/assets/b00e1416-9c3c-4018-810b-7efa2ffa61cc)

> Yes i don't own the Purobot Ultra could check if button action are all working as expected ?
> 
> Thank you

**Comment by Jezza34000** [comment]
Hi, all remark are updated in last release
Can you check ?

**Comment by JrothSKV** [comment]
Looking better! Main problem seems to be that the ultra integration isn't logging any event activity except wastebin, probably due to missing sensors/diagnostics. My guess. So "cat activity", cleaning events, "last used by", "times used" etc aren't appearing in the log. "Last event" may be the key one to logging these is my guess. Also the litter dumping conteols were removed from the max.

Ultra sensors
![image](https://github.com/user-attachments/assets/7710bf4a-a7af-439e-b243-aed3170f66f9)

Pura max sensors
![image](https://github.com/user-attachments/assets/11006a9f-b6e5-4474-8df5-d1749798c7a5)

Pura max diagnostics
![image](https://github.com/user-attachments/assets/a3d2d2bc-56ee-4ae5-ae66-0ac111558d4a)

Pura ultra diagnostics

![image](https://github.com/user-attachments/assets/b321c38f-bc0b-47c6-a7fd-92b36ab00d97)


> Hi @JrothSKV , all remark are updated in last release
> 
> Can you check ?

**Comment by Jezza34000** [comment]
Hi, for the PuraMax I put back the missing buttons. As for the statistics I have not yet investigated, the Purobot has a new, completely different endpoint

**Comment by JrothSKV** [comment]
Here's one error I see in the logs if it helps:

2024-11-29 10:25:45.955 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/config/custom_components/petkit/sensor.py", line 2465, in _handle_coordinator_update
    sorted_dict = self.grab_recent_duration()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petkit/sensor.py", line 2492, in grab_recent_duration
    if lb_data.statistics['statisticInfo']:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'statisticInfo'

> Hi, for the PuraMax I put back the missing buttons. As for the statistics I have not yet investigated, the Purobot has a new, completely different endpoint

**Comment by Jezza34000** [comment]
Yes I've fixed this as well but I didn't release last push for now

**Comment by Jezza34000** [comment]
Check this release should fix many stuff
https://github.com/Jezza34000/home-assistant-petkit/releases/tag/v1.2.0

**Comment by Jezza34000** [comment]
Hi !
I've done a complete rewrite don't use this repository anymore.
Please use the new one available here : 
https://github.com/Jezza34000/homeassistant_petkit
